version: '3.9'

services:
  postgres:
    image: postgres
    platform: linux/amd64
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: first-kotlin-app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

volumes:
  pgdata: